[platformio]
src_dir = main

[env:remote01]
platform = espressif32@6.13.0
platform_packages =
    platformio/framework-espidf@3.50503.0
    platformio/toolchain-xtensa-esp-elf@14.2.0+20251107
board = esp32-s3-devkitc-1
framework = espidf
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.sdkconfig_defaults = sdkconfig.defaults
monitor_speed = 115200
